module.exports = Object.freeze({
	ACTION_PATH: [
		'go',
		'stop',
		'pause',
		'restart',
		'resume',
		'move',
		'fade',
		'cueposition',
		'jump',
		'pan',
		'volume',
		'speed',
		'track',
	],
	TARGET_PATH: ['playhead', 'active', 'cue'],
	NAVIGATION_PATH: ['first', 'last', 'prev', 'next', 'cue'],
	ACTION_CHOICES: [
		{ id: 'go', label: 'GO' },
		{ id: 'stop', label: 'STOP' },
		{ id: 'pause', label: 'PAUSE' },
		{ id: 'restart', label: 'RESTART' },
		{ id: 'resume', label: 'RESUME' },
		{ id: 'select', label: 'MOVE PLAYHEAD' },
		{ id: 'fade', label: 'FADE' },
		{ id: 'cuepoint', label: 'CUE POSITION' },
		{ id: 'jump', label: 'JUMP TO' },
		{ id: 'pan', label: 'PAN' },
		{ id: 'volume', label: 'VOLUME' },
		{ id: 'speed', label: 'SPEED' },
		{ id: 'track', label: 'TRACK' },
	],
	TARGET_ALL_CHOICES: [
		{ id: 'playhead', label: 'CURRENT' },
		{ id: 'cue', label: 'CUE' },
		{ id: 'active', label: 'ALL' },
	],

	TARGET_CHOICES: [
		{ id: 'playhead', label: 'CURRENT' },
		{ id: 'cue', label: 'CUE' },
	],
})
